<script setup lang="ts">
import { computed } from 'vue'
import AppHeader from '@/components/AppHeader.vue'
import AppFooter from '@/components/AppFooter.vue'

interface Props {
  type: 'privacy' | 'terms'
}

const props = defineProps<Props>()

const isPrivacy = computed(() => props.type === 'privacy')

const privacyContent = {
  title: 'Privacy Policy',
  intro: [
    `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
    `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries.`,
  ],
  sections: [
    {
      title: 'Legal basis',
      type: 'text' as const,
      content: [`Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`],
    },
    {
      title: 'Data collocation and storage',
      type: 'text' as const,
      content: [
        `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.`,
        `It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.`,
      ],
    },
    {
      title: 'What information we collect',
      type: 'list' as const,
      content: [
        'Basic Personal Data: name, surname, job title etc.',
        'Identification information and other background verification data: (your or your representative\'s, ultimate beneficiary owners) – name, surname, personal identity code, date of birth, address, nationality, gender, passport or ID card copy, evidence of beneficial ownership or the source of funds, number of shares held, voting rights or share capital part, title.',
        'Transaction data: beneficiary details, date, time, amount and currency which was used, name/IP address of sender and receiver, accounts, amount of transactions, income, location, etc.',
        'Information related to legal requirements: data resulting from enquiries made by the authorities, data that enables us to perform anti-money laundering requirements and ensure the compliance with international sanctions, including the purpose of the business relationship and whether you are a politically exposed person and other data that is required to be processed by us in order to comply with the legal obligation to "know your client".',
        'Contact Data: registered/actual place of residence, phone number, e–mail address etc.',
      ],
    },
    {
      title: 'Purposes and legal basis for Personal Data processing',
      type: 'mixed' as const,
      intro: 'We collect personal data for the purposes listed below:',
      content: [
        'Conclusion of the contract or for performance of measures at your request prior to the conclusion of the contract (to identify and verify the clients).',
        'We may process your Basic Personal Data, Identification and other background verification Data, Contact Information and other Personal Data (in order to identify the possibility of providing services).',
        'Legal basis: concluding a contract with you, to fulfilling our legitimate interests and/or fulfilling the legal obligations applicable to us.',
        'Fulfilment of a contract concluded with you.',
        'For this purpose, we may process your Basic Personal Data, Identification and other background verification Data, Transaction Data, Information which is related to legal requirements, Contact Information and other Personal Data provided to us by or on behalf of you or generated by us in the course of providing services.',
        'Legal basis: performance of a contract signed with you, fulfilling our or third parties\' legitimate interests and/or compliance with legal obligations applicable to us.',
        'Compliance with legal obligations.',
        'For this purpose, we may process your Basic Personal Data, Identification and other background verification Data, Transaction Data, Information which is related to legal requirements, Contact Information and other Personal Data provided to us by or on behalf of you or generated by us in the course of providing services.',
        'Legal basis: fulfilling our or third parties\' legitimate interests and/or compliance with legal obligations applicable to us.',
        'To provide an answer when you contact us through our website or other communication measures',
        'For this purpose, we may process your Basic Personal Data, Contact Information and other Personal Data provided to us by or on behalf of you.',
        'Legal basis: your consent, fulfilling our or third parties\' legitimate interests.',
      ],
    },
    {
      title: 'Further information',
      type: 'mixed' as const,
      intro: 'We collect personal data for the purposes listed below:',
      content: [
        `If you have any questions, concerns or complaints regarding our compliance with this Privacy Policy and the data protection laws, or if you wish to exercise your rights, we encourage you to first contact us using the contact details below. We will investigate and attempt to resolve complaints and disputes and will make every reasonable effort to honour your wish to exercise your rights as quickly as possible and in any event, within the timescales provided by data protection laws. Any questions, comments and requests regarding this Privacy Policy should be addressed by writing to us at: 1 Christaki Kranou, Germasogeia 4047, Limassol, Cyprus or by sending an e-mail to: info@viviyan.com.`,
      ],
      isLastParagraph: true,
    },
  ],
}

const termsContent = {
  title: 'Terms and Conditions',
  intro: [
    `These Terms and Conditions govern your use of the services provided by VIVIYAN CORP LIMITED. By accessing or using our services, you agree to be bound by these Terms. Please read them carefully before proceeding.`,
    `VIVIYAN CORP LIMITED reserves the right to modify these Terms at any time. We will notify you of any changes by posting the new Terms on this page. Your continued use of the services after any changes constitutes your acceptance of the new Terms.`,
  ],
  sections: [
    {
      title: 'Acceptance of Terms',
      type: 'text' as const,
      content: [`By accessing and using the services of VIVIYAN CORP LIMITED, you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions. If you do not agree to these Terms, please do not use our services.`],
    },
    {
      title: 'Services Description',
      type: 'text' as const,
      content: [
        `VIVIYAN CORP LIMITED provides business consulting and support services designed to help companies improve their operations, workflows, and overall business performance.`,
        `We reserve the right to modify, suspend, or discontinue any aspect of our services at any time without prior notice.`,
      ],
    },
    {
      title: 'User Obligations',
      type: 'list' as const,
      content: [
        'You must provide accurate and complete information when engaging with our services.',
        'You agree not to use our services for any unlawful purpose or in violation of any applicable laws.',
        'You are responsible for maintaining the confidentiality of any account credentials.',
        'You must not attempt to gain unauthorized access to any part of our services or systems.',
        'You agree to notify us immediately of any unauthorized use of your account.',
      ],
    },
    {
      title: 'Intellectual Property',
      type: 'mixed' as const,
      intro: 'All intellectual property rights in our services and content are owned by VIVIYAN CORP LIMITED:',
      content: [
        'All content, trademarks, and other intellectual property displayed on our platform are the property of VIVIYAN CORP LIMITED.',
        'You may not reproduce, distribute, or create derivative works without our express written permission.',
        'Any feedback or suggestions you provide may be used by us without any obligation to you.',
        'We grant you a limited, non-exclusive license to use our services for your internal business purposes.',
      ],
    },
    {
      title: 'Contact Information',
      type: 'mixed' as const,
      intro: 'For any questions regarding these Terms and Conditions:',
      content: [
        `If you have any questions about these Terms and Conditions, please contact us at: 1 Christaki Kranou, Germasogeia 4047, Limassol, Cyprus or by sending an e-mail to: info@viviyan.com.`,
      ],
      isLastParagraph: true,
    },
  ],
}

const content = computed(() => isPrivacy.value ? privacyContent : termsContent)
</script>

<template>
  <div class="legal">
    <AppHeader />
    <main class="legal__main">
      <div class="legal__container">
        <h1 class="legal__title">{{ content.title }}</h1>

        <div class="legal__content">
          <!-- Intro paragraphs -->
          <div class="legal__block">
            <p
              v-for="(para, i) in content.intro"
              :key="i"
              class="legal__text"
            >{{ para }}</p>
          </div>

          <!-- Sections -->
          <div
            v-for="section in content.sections"
            :key="section.title"
            class="legal__block"
          >
            <h2 class="legal__section-title">{{ section.title }}</h2>

            <!-- Plain text -->
            <template v-if="section.type === 'text'">
              <p
                v-for="(para, i) in section.content"
                :key="i"
                class="legal__text"
              >{{ para }}</p>
            </template>

            <!-- Bullet list -->
            <template v-else-if="section.type === 'list'">
              <ul class="legal__list">
                <li
                  v-for="(item, i) in section.content"
                  :key="i"
                  class="legal__list-item"
                >{{ item }}</li>
              </ul>
            </template>

            <!-- Mixed: intro + list or paragraph -->
            <template v-else-if="section.type === 'mixed'">
              <p v-if="section.intro" class="legal__text">{{ section.intro }}</p>
              <template v-if="section.isLastParagraph">
                <p
                  v-for="(item, i) in section.content"
                  :key="i"
                  class="legal__text"
                >
                  <template v-if="item.includes('info@viviyan.com')">
                    {{ item.split('info@viviyan.com')[0] }}<a href="mailto:info@viviyan.com" class="legal__email">info@viviyan.com.</a>
                  </template>
                  <template v-else>{{ item }}</template>
                </p>
              </template>
              <ul v-else class="legal__list">
                <li
                  v-for="(item, i) in section.content"
                  :key="i"
                  class="legal__list-item"
                >{{ item }}</li>
              </ul>
            </template>
          </div>
        </div>
      </div>
    </main>
    <AppFooter />
  </div>
</template>

<style scoped lang="scss">
.legal {
  display: flex;
  flex-direction: column;
  min-height: 100vh;
  background-color: #111;

  &__main {
    flex: 1;
    padding: 160px 200px 100px;

    @media (max-width: 1023px) {
      padding: 120px 80px 80px;
    }

    @media (max-width: 767px) {
      padding: 100px 16px 60px;
    }
  }

  &__container {
    max-width: 1040px;
    width: 100%;
    margin: 0 auto;
    display: flex;
    flex-direction: column;
    gap: 80px;

    @media (max-width: 1023px) {
      gap: 60px;
    }

    @media (max-width: 767px) {
      gap: 40px;
    }
  }

  &__title {
    font-family: var(--font-display);
    font-variation-settings: 'opsz' 14, 'wdth' 100;
    font-weight: 700;
    font-size: 64px;
    line-height: 80px;
    color: #faf4f1;
    text-align: center;

    @media (max-width: 1023px) {
      font-size: 48px;
      line-height: 56px;
    }

    @media (max-width: 767px) {
      font-size: 36px;
      line-height: 44px;
      text-align: left;
    }
  }

  &__content {
    display: flex;
    flex-direction: column;
    gap: 64px;

    @media (max-width: 767px) {
      gap: 40px;
    }
  }

  &__block {
    display: flex;
    flex-direction: column;
    gap: 32px;

    @media (max-width: 767px) {
      gap: 20px;
    }
  }

  &__section-title {
    font-family: var(--font-display);
    font-variation-settings: 'opsz' 14, 'wdth' 100;
    font-weight: 700;
    font-size: 40px;
    line-height: 48px;
    color: #faf4f1;

    @media (max-width: 1023px) {
      font-size: 32px;
      line-height: 40px;
    }

    @media (max-width: 767px) {
      font-size: 24px;
      line-height: 32px;
    }
  }

  &__text {
    font-family: var(--font-body);
    font-size: 18px;
    font-weight: 300;
    line-height: 24px;
    color: #bfbfbf;

    & + & {
      margin-top: 16px;
    }

    @media (max-width: 767px) {
      font-size: 16px;
    }
  }

  &__list {
    list-style: disc;
    padding-left: 27px;
    display: flex;
    flex-direction: column;
    gap: 8px;
  }

  &__list-item {
    font-family: var(--font-body);
    font-size: 18px;
    font-weight: 300;
    line-height: 24px;
    color: #bfbfbf;

    @media (max-width: 767px) {
      font-size: 16px;
    }
  }

  &__email {
    color: #ffcb3c;
    text-decoration: underline;
  }
}
</style>
